frontend/models/penumpang.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "penumpang".
 *
 * @property string $barcode
 * @property int $NIK
 * @property string $id_user
 * @property string $id_tiket
 * @property int $jumlah_penumpang
 * @property string $no_polisi
 *
 * @property Manifest[] $manifests
 * @property User $user
 * @property Tiket $tiket
 * @property Tiket[] $tikets
 */
class penumpang extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'penumpang';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['barcode', 'NIK', 'id_user', 'jumlah_penumpang', 'no_polisi'], 'required'],
            [['NIK', 'jumlah_penumpang'], 'integer'],
            [['barcode', 'id_user'], 'string', 'max' => 64],
            [['no_polisi'], 'string', 'max' => 11],
            [['barcode', 'NIK'], 'unique', 'targetAttribute' => ['barcode', 'NIK']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id_user']]
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'barcode' => 'Barcode',
            'NIK' => 'NIK',
            'id_user' => 'Id User',
            'jumlah_penumpang' => 'Jumlah Penumpang',
            'no_polisi' => 'No Polisi',
        ];
    }
    public function setId()
    {
        $this->id = Yii::$app->security->generateRandomString(64);
    }

    public function setBarcode()
    {
        $this->barcode = Yii::$app->security->generateRandomString(64);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getManifests()
    {
        return $this->hasMany(Manifest::className(), ['barcode' => 'barcode']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_user' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTiket()
    {
        return $this->hasOne(Tiket::className(), ['id_tiket' => 'id_tiket']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTikets()
    {
        return $this->hasMany(Tiket::className(), ['barcode' => 'barcode']);
    }
}

frontend/controllers/PenumpangController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\penumpang;
use frontend\models\search\penumpangSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PenumpangController implements the CRUD actions for penumpang model.
 */
class PenumpangController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all penumpang models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new penumpangSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single penumpang model.
     * @param string $barcode
     * @param integer $NIK
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($barcode, $NIK)
    {
        return $this->render('view', [
            'model' => $this->findModel($barcode, $NIK),
        ]);
    }

    /**
     * Creates a new penumpang model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new penumpang();

        if ($model->load(Yii::$app->request->post())) 
        {
            $model->setId();
            $model->setBarcode();
            $model->id_user = Yii::$app->user->getId();
            return $this->redirect(['view', 'barcode' => $model->barcode, 'NIK' => $model->NIK]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing penumpang model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $barcode
     * @param integer $NIK
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($barcode, $NIK)
    {
        $model = $this->findModel($barcode, $NIK);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'barcode' => $model->barcode, 'NIK' => $model->NIK]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing penumpang model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $barcode
     * @param integer $NIK
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($barcode, $NIK)
    {
        $this->findModel($barcode, $NIK)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the penumpang model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $barcode
     * @param integer $NIK
     * @return penumpang the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($barcode, $NIK)
    {
        if (($model = penumpang::findOne(['barcode' => $barcode, 'NIK' => $NIK])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/TiketController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\tiket;
use frontend\models\search\tiketSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\TiketForm;
use frontend\models\User;
use frontend\models\Jadwal;
use frontend\models\Penumpang;
use frontend\models\harga_tiket;
use frontend\models\kapal;
use kartik\mpdf\Pdf;

/**
 * TiketController implements the CRUD actions for tiket model.
 */
class TiketController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all tiket models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new tiketSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single tiket model.
     * @param string $id_tiket
     * @param string $barcode
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id_tiket, $barcode)
    {
        return $this->render('view', [
            'model' => $this->findModel($id_tiket, $barcode),
        ]);
    }

    /**
     * Creates a new tiket model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TiketForm();
        $user = new user();
        $tiket = new tiket();

        $hargatiket = new harga_tiket();
        $penumpang = new Penumpang();
        if ($model->load(Yii::$app->request->post())) {
             $penumpang->setBarcode();
             $penumpang->NIK = $model->NIK;
             $penumpang->id_user = Yii::$app->user->getId();
             $penumpang->jumlah_penumpang = $model->jumlah_penumpang;
             $penumpang->no_polisi = $model->no_polisi;

             $penumpang->save(); // solve :)
              $tiket->setId();
              $tiket->barcode =  $penumpang->barcode;
              $tiket->id_user = Yii::$app->user->getId();
            $kendaraan = harga_tiket::find()
                ->where(['id_harga_tiket' => $model->jenis_kendaraan])
                ->one();     
            $jadwalid = jadwal::find()
                ->where(['asal' => $model->asal, 'tujuan' => $model->tujuan, 'trip' =>$model->trip])
                ->one();
            $tiket->id_jadwal = $jadwalid->id_jadwal;
            $tiket->id_kapal = $model->kapal;
            $tiket->id_harga_tiket = $model->jenis_kendaraan;
            $jenis_kendaraan = $kendaraan->jenis_kendaraan;
            $tiket->tanggal_keberangkatan = $model->tanggal_keberangkatan;
            $tiket->status_keberangkatan = 1;
            $tiket->total_harga = $kendaraan->harga_tiket + (($model->jumlah_penumpang)-1)*10000 ;
            $tiket->waktu_transaksi = date('Y:m:d H:i:s',strtotime('+5Hours'));
            $tiket->save(false);
            //Yii::$app->session->setFlash('success', 'Tiket  ' .$model->NIK. ' berhasil dibuat');
            return $this->actionPrintTiket();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing tiket model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id_tiket
     * @param string $barcode
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id, $barcode)
    {
        $model = $this->findModel($id, $barcode);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id_tiket' => $model->id, 'barcode' => $model->barcode]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing tiket model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id_tiket
     * @param string $barcode
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id, $barcode)
    {
        $this->findModel($id, $barcode)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the tiket model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id_tiket
     * @param string $barcode
     * @return tiket the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $barcode)
    {
        if (($model = tiket::findOne(['id_tiket' => $id, 'barcode' => $barcode])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionPrintTiket()
    {
        $model = new TiketForm();
        if ($model->load(Yii::$app->request->post())) {
            $kendaraan = harga_tiket::find()
            ->where(['id' => $model->jenis_kendaraan])
            ->one();
        $jenis_kendaraan = $kendaraan->jenis_kendaraan;
        $harga = $kendaraan->harga_tiket + (($model->jumlah_penumpang)-1)*10000 ;
        $pdf_content = $this->renderPartial('cetak', [
            'model' => $model,
            'jenis_kendaraan' => $jenis_kendaraan,
            'harga' => $harga,
        ]);
        }
        $mpdf = new \Mpdf\Mpdf();
        $mpdf->showImageErrors = true;
        $mpdf->WriteHTML($pdf_content);
        $mpdf->Output();
        exit;
    }
}

frontend/views/penumpang/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\penumpang */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="penumpang-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'NIK')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'jumlah_penumpang')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'no_polisi')->textInput(['autofocus' => true]) ?>
                <div style="text-align:right; width:100%; padding:0;">
                <div class="form-group">
                    <?= Html::submitButton('Simpan', ['class' => 'btn btn-success']) ?>
                    <?= Html::a('Batal', ['/tiket/index'], ['class'=>'btn btn-primary']) ?>
                </div> </div>
    <?php ActiveForm::end(); ?>

</div>

frontend/views/penumpang/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\search\penumpangSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="penumpang-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'barcode') ?>

    <?= $form->field($model, 'NIK') ?>

    <?= $form->field($model, 'id_user') ?>

    <?= $form->field($model, 'id_tiket') ?>

    <?= $form->field($model, 'jumlah_penumpang') ?>

    <?php // echo $form->field($model, 'no_polisi') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/penumpang/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\penumpang */

$this->title = 'Create Penumpang';
$this->params['breadcrumbs'][] = ['label' => 'Penumpangs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="penumpang-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/penumpang/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use dosamigos\chartjs\ChartJs;
use frontend\models\Penumpang;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\search\penumpangSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Penumpang';
$this->params['breadcrumbs'][] = $this->title;

$a = array();
$rows = (new \yii\db\Query())
    ->select(['jumlah_penumpang'])
    ->from('penumpang')
    ->all();


for($i = 0 ; $i < count($rows) ; $i++){
    array_push($a, $rows[$i]['jumlah_penumpang']);
}

$res = (new \yii\db\Query())
    ->select(['sum(jumlah_penumpang) as jumlah', 'tanggal_keberangkatan'])
    ->from('tiket')
    ->join('INNER JOIN', 'penumpang', 'tiket.barcode = penumpang.barcode')
    ->groupBy('tanggal_keberangkatan')
    ->all();

$jumlah = array();
$tanggal = array();
for($i = 0 ; $i < count($res) ; $i++){
    array_push($jumlah, $res[$i]['jumlah']);
    array_push($tanggal, $res[$i]['tanggal_keberangkatan']);
}

?>
<div class="penumpang-index">

    <?= ChartJs::widget([
    'type' => 'line',
    'options' => [
        'height' => 150,
        'width' => 300
    ],
    'data' => [
        'labels' => $tanggal,
        'datasets' => [
            [
                'label' => "Jumlah Penumpang",
                'backgroundColor' => "rgba(179,181,198,0.2)",
                'borderColor' => "rgba(179,181,198,1)",
                'pointBackgroundColor' => "rgba(179,181,198,1)",
                'pointBorderColor' => "#fff",
                'pointHoverBackgroundColor' => "#fff",
                'pointHoverBorderColor' => "rgba(179,181,198,1)",
                'data' => $jumlah,
            ]
        ]
    ]
]);
?>


</div>

frontend/views/penumpang/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\penumpang */

$this->title = 'Update Penumpang: ' . $model->barcode;
$this->params['breadcrumbs'][] = ['label' => 'Penumpangs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->barcode, 'url' => ['view', 'barcode' => $model->barcode, 'NIK' => $model->NIK]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="penumpang-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/penumpang/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\penumpang */

$this->title = $model->barcode;
$this->params['breadcrumbs'][] = ['label' => 'Penumpangs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="penumpang-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'barcode' => $model->barcode, 'NIK' => $model->NIK], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'barcode' => $model->barcode, 'NIK' => $model->NIK], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'barcode',
            'NIK',
            'id_user',
            'id_tiket',
            'jumlah_penumpang',
            'no_polisi',
        ],
    ]) ?>

</div>