backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/KapalController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\kapal;
use frontend\models\PerubahanKapal;
use frontend\models\KapalForm;
use frontend\models\search\kapalSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * KapalController implements the CRUD actions for kapal model.
 */
class KapalController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all kapal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new kapalSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single kapal model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new kapal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new KapalForm();
        $kapal = new kapal();
        if ($model->load(Yii::$app->request->post())) {
            $kapal->setId();
            $kapal->nama = $model->nama;
            $kapal->tahun_keluaran = $model->tahun_keluaran;
            $kapal->jumlah_muatan = $model->jumlah_muatan;
            $kapal->save();
                Yii::$app->session->setFlash('success', 'Kapal berhasil dibuat');
                return $this->redirect(['kapal/index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing kapal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model_perubahan = new PerubahanKapal();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        $model_perubahan->setId();
        $model_perubahan->id_user = Yii::$app->user->getId();
        $model_perubahan->id_kapal = $model->id;
        $model_perubahan->waktu_perubahan_kapal = date('Y:m:d H:i:s',strtotime('+5Hours'));
        $model_perubahan->save();

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing kapal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the kapal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return kapal the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = kapal::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findModelJadwal($id)
    {
        if (($model = jadwal::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\user;
use frontend\models\UserForm;
use frontend\models\search\userSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for user model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all user models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new userSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single user model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new user model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserForm();
        $user = new user();

        if ($model->load(Yii::$app->request->post())) {
            $user->setId();
            $user->nama_lengkap = $model->nama_lengkap;
            $user->tanggal_lahir= $model->tanggal_lahir;
            $user->tempat_lahir = $model->tempat_lahir;
            $user->alamat = $model->alamat;
            $user->no_hp = $model->no_hp;
            // var_dump($model->no_hp);
            // die();
            $user->username = $model->username;
            $user->password = Yii::$app->security->generatePasswordHash($model->password);
            $user->role = "3";
            $user->pertanyaan_pemulihan =  $model->pertanyaan_pemulihan;
            $user->jawaban_pemulihan = $model->jawaban_pemulihan;
            // var_dump($model->jawaban_pemulihan,$model->pertanyaan_pemulihan);
            // die();
            $user->waktu_pembuatan =  date('Y:m:d H:i:s',strtotime('+5Hours'));
            $user->last_login=  date('Y:m:d H:i:s',strtotime('+5Hours'));
            $user->waktu_perubahan_password =  date('Y:m:d H:i:s',strtotime('+5Hours'));

            $user->save();

                    Yii::$app->session->setFlash('success', 'Akun  ' .$model->username. ' berhasil dibuat');
                    return $this->redirect(['user/index']);
            } 
            

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing user model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_user]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing user model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the user model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return user the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = user::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/kapal.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;


$this->title = 'Kapal';
?>
<div class="site-kapal">
    
    <div class="row">
        <h3> Buat Data Kapal </h3>
      
        <div class="col-lg-7">
            
            <?php $form = ActiveForm::begin(['id' => 'form-kapal']); ?>

                <?= $form->field($model, 'nama_kapal')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'tahun_kapal')->textInput(['autofocus' => true]) ?>

                 <?= $form->field($model, 'jumlah_muatan')->textInput(['autofocus' => true]) ?>
                 <?= $form->field($model, 'pendapatan_kapal')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'tujuan[]')->dropDownList(
                            ['a' => '', 'b' => 'Truk', 'c' => 'Mobil']
                    ); ?>
                <?= $form->field($model, 'jadwal_kapal[]')->dropDownList(
                            ['a' => '', 'b' => 'Truk', 'c' => 'Mobil']
                    ); ?>
               
               
                
                   <?= Html::button('Batal', ['class' => 'btn btn-primary', 'name' => 'kapalbatal-button']) ?>
                  
                    <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary', 'name' => 'kapalsimpan-button']) ?>
                </div>
               
            <?php ActiveForm::end(); ?>
        </div>
        
          
        
    </div>
               
</div>

frontend/views/site/kapalsearch.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\search\kapalSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="kapal-search">

   <div style="text-align:right; width:100%; padding:0;">
    
   <?= Html::a('Tambah Kapal', ['/kapal/create'], ['class'=>'btn btn-primary']) ?>

    </div>
    <div class="form-group">  
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    </div>

    

    <?= $form->field($model, 'cari')->textInput(['autofocus' => true]) ?>
    
    
   

   


    <?php ActiveForm::end(); ?>

</div>

frontend/views/site/kendaraanjadwal.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;


$this->title = 'Kendaraan & Jadwal';
?>
<div class="site-kendaraanjadwal">
    
    <div class="row">
       
               <div class="col-lg-7">
       
            <?php $form = ActiveForm::begin(['id' => 'form-pegawailoket']); ?>
            <div id="pilihan">
            <?= $form->field($model, 'pilihan[]')->dropDownList(
                            ['a' => 'kendaraan', 'b' => 'jadwal']
                    ); ?>
            </div>
         
                <div id="jadwal">
                <?= $form->field($model, 'jenis')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'golongan')->textInput(['autofocus' => true]) ?>
                </div>
                <div class="form-group">
                    <?= Html::submitButton('Batal', ['class' => 'btn btn-primary', 'name' => 'pegawailoketbatal-button']) ?>
                    <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary', 'name' => 'pegawailoketsimpan-button']) ?>
                </div>
               
            <?php ActiveForm::end(); ?>
        </div>
        
          
        
    </div>
               
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';

?>
<style>

    .radius{
        border-radius: 50px;
        padding: 10px;
    }
</style>
    
<div class="row">    

        <div class="col-lg-3"></div>
        <div class="col-lg-5">
        <h1><?= Html::encode($this->title) ?></h1>
        
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            
                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>
                
                <div class="col-left">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                
</div>

                

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
</div>

frontend/views/site/pegawailoketsearch.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\search\pegawai_loketSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pegawai-loket-search">

   <div style="text-align:right; width:100%; padding:0;">
    
   <?= Html::a('Tambah Akun', ['/user/create'], ['class'=>'btn btn-primary']) ?>

    </div>
    <div class="form-group">  
    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    </div>

    

    <?= $form->field($model, 'cari')->textInput(['autofocus' => true]) ?>
    
    
   

   


    <?php ActiveForm::end(); ?>

</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

            <?= $form->field($model, 'pertanyaan_pemulihan')->dropDownList(
                            ['Apa warna kesukaan anda?' => 'Apa warna kesukaan anda?', 'Apa hewan kesukaan anda?' => 'Apa hewan kesukaan anda?', 'Apa lagu kesukaan anda sepanjang masa?' => 'Apa lagu kesukaan anda sepanjang masa?']
                    ); ?>
                <?= $form->field($model, 'jawaban_pemulihan')->textInput(['maxlength' => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resendVerificationEmail.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Resend verification email';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-resend-verification-email">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A verification email will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'resend-verification-email-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use dosamigos\datepicker\DatePicker;

$this->title = 'Tiket';
?>
<div class="site-signup">
    
    <div class="row">
        
        <div class="col-lg-5">
            
            <?php $form = ActiveForm::begin(['id' => 'form-tiket']); ?>

                <?= $form->field($model, 'NIK')->textInput(['autofocus' => true]) ?>
                
                <?= $form->field($model, 'jenis_kendaraan[]')->dropDownList(
                            ['a' => '', 'b' => 'Truk', 'c' => 'Mobil']
                    ); ?>
                <?= $form->field($model, 'jumlah_penumpang')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'tujuan')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'no_polisi')->textInput(['autofocus' => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>
               
            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-lg-1"></div>
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                               
                <?= $form->field($model, 'tanggal_keberangkatan')->widget(
                    DatePicker::className(), [
                        // inline too, not bad
                        'inline' => false, 
                        // modify template for custom rendering
                        //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
                        'clientOptions' => [
                            'autoclose' => true,
                            'format' => 'dd-M-yyyy'
                        ]
                ]);?>

                <?php
                echo $form->field($model, 'jam_keberangkatan[]')->dropDownList(
                            ['a' => '', 'b' => '08:00', 'c' => '13:00']
                    ); ?>

                
               
             
            <?php ActiveForm::end(); ?>
        </div>
    </div>
                </form>
</div>

frontend/views/site/tiket.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use dosamigos\datepicker\DatePicker;

$this->title = 'Tiket';
?>
<div class="site-signup">
    
    <div class="row">
        
        <div class="col-lg-5">
            
            <?php $form = ActiveForm::begin(['id' => 'form-tiket']); ?>

                <?= $form->field($model, 'NIK')->textInput(['autofocus' => true]) ?>
                
                <?= $form->field($model, 'jenis_kendaraan[]')->dropDownList(
                            ['a' => ' ','b' => 'Tidak ada', 'c' => 'Truk', 'd' => 'Mobil']
                    ); ?>
                <?= $form->field($model, 'jumlah_penumpang')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'tujuan')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'no_polisi')->textInput(['autofocus' => true]) ?>
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div> 
               
            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-lg-1"></div>
            <div class="col-lg-5">
                <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
         
                    <?= $form->field($model, 'tanggal_keberangkatan')->widget(
                        DatePicker::className(), [
                            // inline too, not bad
                            'inline' => false, 
                            // modify template for custom rendering
                            //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
                            'clientOptions' => [
                                'autoclose' => true,
                                'format' => 'dd-M-yyyy'
                            ]
                    ]);?>

                    <?php
                    echo $form->field($model, 'jam_keberangkatan[]')->dropDownList(
                                ['a' => '', 'b' => '08:00', 'c' => '13:00']
                        ); ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>